baseURL = 'https://blog.candace.cloud/'
languageCode = 'en-us'
title = 'candaceblog'
theme = 'candace'

[params]
author = 'Skanda Kaashyap'
github = 'kaashmonee'
email = 'skandakk a t gmail d o t com'

[params.social]
linkedin = 'https://linkedin.com/in/yourprofile'
twitter = '@yourusername'
